EO-609 update employee screens
effectivemade/Effective-Office pull request #291
Opened 2024-10-28 11:37 UTC by Qiraa

Change design and add lib for visual transformation of phone number

2024-11-05 07:25 UTC, TheGood77 approved these changes

2024-11-05 08:11 UTC, Radch-enko commented on composeApp/build.gradle.kts
> +                implementation(libs.libphonenumber)
Посмотри вот это решение - https://stackoverflow.com/questions/71274129/phone-number-visual-transformation-in-jetpack-compose

Лучше по минимуму затаскивать либы в проект

2024-11-05 08:13 UTC, Radch-enko commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/InfoAboutUserUIComponent.kt
> +fun InfoAboutUserUIComponent(
Слишком перегруженное название. Понятно что оно было до тебя, но все же поправляйте по ходу такие вещи. Если это экран профиля, то как будто достаточно `ProfileScreen` или `UserScreen`

2024-11-05 08:14 UTC, Radch-enko commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/InfoAboutUserUIComponent.kt
> +        Spacer(modifier = Modifier.height(4.dp))
Отступ можно переместить тоже под `post?.let {` 
Если post будет null то отступ по сути не нужен будет

2024-11-05 08:15 UTC, Radch-enko commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/InfoAboutUserUIComponent.kt
> +                fontSize = 16.sp,
вроде стиль шрифта указан, а размер шрифта все равно ручками прописывается? Проверь, тот ли стиль используешь, либо заведи новый

2024-11-05 08:17 UTC, Radch-enko commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/Employee.kt
> +            is FullEmployeeComponent.Child.AboutEmployeeChild -> AboutEmployeeScreen(child.component)
Можно пока не фиксить, но примите к сведению:`About` - приставки не несут смысловой нагрузки. Надо будет переименовать (все фичевые компоненты в иерархии, т.е. модельки, компоуз функции, эффекты и экшены и тд)

2024-11-05 08:19 UTC, Radch-enko commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/aboutEmployee/components/BookingCardUser.kt
> +                fontSize = 18.sp,
надо развивать дизайн систему в проекте, чтобы ручками не указывать каждый раз эти шрифты. Все надо брать из Typography. Обсудите с командой

2024-11-05 08:20 UTC, Radch-enko commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/aboutEmployee/components/EmployeeInfoRow.kt
> +fun EmployeeInfoRow(
Можно не фиксить: `Row` как будто лишнее в названии, но можно обсудить

2024-11-05 08:22 UTC, Radch-enko commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/aboutEmployee/components/EmployeeInfoRow.kt
> +                onLongClick = { onLongClick() },
не уверен, но по идее здесь можно просто : 
```
onLongClick = onLongClick, 
onClick = onClick
```

так лаконичнее)))

2024-11-05 08:26 UTC, Radch-enko commented
Я так понял вы приступили к редизайну. Попросите дизайнера отрисовать основные элементы дизайн системы, все возможные шрифты и тд. Важно чтобы итоговые дизайны экранов строились из этих компонентов. 

Тогда вы можете разработать по дизайн системе все эти вьюшки, заложить все возможные шрифты в тему и использовать при разработке. Это сильно проще и быстрее. 

Сейчас вы ручками будете прописывать жирность , размер шрифта и тд, если шрифты в дизайне поменяются, вам придется опять проходить по всем экранам и менять (правильный вариант: поменять в базовом компоненте)

2024-11-05 08:29 UTC, Radch-enko commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/allEmployee/EmployeeScreen.kt
> +                .background(theme_light_onPrimary)
Надо брать из темы по максимуму. 
Я видел по дизайну планируется еще темная тема. 

Если сейчас наклипаете цвета как здесь, то потом будет сложно и долго внедрять темную тему да и в целом что-то редизайнить)

2024-11-05 08:33 UTC, Radch-enko requested changes
- Попробуй сделать маску без либы
- Ренейминг делать не стоит в этом реквесте (но в голове держите что с каждым реквестом надо улучшать кодовую базу)
- Хардкодные цвета, шрифты по максимуму вынести в тему (там где-то имеет смысл - основные популярные цвета фонов, кнопок и тд)

2024-11-05 10:43 UTC, Qiraa commented
> Я так понял вы приступили к редизайну. Попросите дизайнера отрисовать основные элементы дизайн системы, все возможные шрифты и тд. Важно чтобы итоговые дизайны экранов строились из этих компонентов. 
> 
> Тогда вы можете разработать по дизайн системе все эти вьюшки, заложить все возможные шрифты в тему и использовать при разработке. Это сильно проще и быстрее. 
> 
> Сейчас вы ручками будете прописывать жирность , размер шрифта и тд, если шрифты в дизайне поменяются, вам придется опять проходить по всем экранам и менять (правильный вариант: поменять в базовом компоненте)

Я попросила отдельно завести задачу, чтоб сделать тему, потому что с тем, что есть сейчас - крайне тяжело работать.

2024-11-11 10:31 UTC, Radch-enko approved these changes

2024-11-11 10:58 UTC, merged