Mobile/feature/fix ios crash on click button close
effectivemade/Effective-Office pull request #294
Opened 2024-11-21 09:54 UTC by TheGood77

In This PR, fix crash app on iOS when choosing time.

2024-11-22 10:11 UTC, Qiraa approved these changes

2024-11-22 19:47 UTC, Radch-enko requested changes
Убери из комитета фалй который не связанны с задачей. Поправьте gitignore

2024-11-22 19:47 UTC, Radch-enko commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/bottomSheets/bookingSheet/bookAccept/store/BookAcceptStoreFactory.kt
> +                            close()
Давай попробуем вынести метод навигации на уровень компоуза. Тогда не придется указывать контекст диспатчера

2024-12-06 11:55 UTC, Radch-enko approved these changes

2024-12-09 08:09 UTC, merged